### ISSUE TITLE
ContentSecurityPolicy Bug: when loading the hamburger menu image

### ISSUE THREAD

**Issue by a1300** [GNYIO/gny-explorer#155]
The hamburger menu can't be loaded due to a `CSP` HTTP Header problem

Error message in console:

![Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml;charset=utf-8,%3Csvg … (“default-src”).](https://user-images.githubusercontent.com/11912239/166488548-30596728-b59a-46f8-8003-56b3b9c49fba.png)

![image](https://user-images.githubusercontent.com/11912239/166488405-e8b473ac-7a09-4c54-81b6-f16ccf49806b.png)

The current `CSP` HTTP header is:
```
content-security-policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' *.gny.io;
```

**Comment by a1300** [comment]
Fixed in commit a81b69cb7ea6e226d762b02a8529b2471030a1fa

The problem was that the hamburger menu was using a `data:` as source. The loading of the `data:` source was prohibited by the CSP. Solution was to directly embed the `svg`


```css
.navbar-light .navbar-toggler-icon {
	background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='30' height='30'%3E%3Cpath stroke='rgba(0, 0, 0, 0.5)' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
}
```
</br>

------------
It works again:

![grafik](https://user-images.githubusercontent.com/11912239/217751504-04e06156-b1df-4fcc-baea-2315b1b6765c.png)
